# Welcome to Jekyll!

# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: We are Getting Married!
description: We are getting married! We want to holler from the rooftops - "Wheeeee! <br><br>Check out this fabulous love we have found!" We want to take a serious moment to publicly speak of our love and commitments to each other. We want to share stories, and create new ones with you. 
owner:
  name: Mike Gifford & Rebecca Wolsak
  email: mike@openconcept.ca

  url: http://randm.news/
first_published: 2018 
baseurl: "/" # the subpath of your site, e.g. /blog
passhash: f9f742e1f653a74c4cd78d7ea283b5556539b96b


BASE_PATH : http://randm.news/4df0179dda01538c9eedcafb8789c0805e4fd0c4

relative_permalinks: false

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome!  
  text: This is the site for all information related to Mike & Rebecca's 2018 celebrations. Here you will find everything you need to join us in Ottawa, Vancouver and/or Thailand!

# - title for your blog's featured posts
# features-title: Ottawa
# features-title2: Vancouver
# features-title3: Thailand
# features-title4: FAQ - added afterwards

# - displayed at the bottom
closing-head: We hope you can help us celebrate!
# closing-para: We need you to RSVP!

# on all pages (and the first three you list display with greeting, if included)
social:
  # twitter: https://twitter.com/mgifford
  # github: https://github.com/mgifford
  # facebook-official: https://facebook.com/gary.faircloth
  # email: /contact/
  heart: mailto:dancingrebecca@gmail.com, mike@openconcept.ca
  flickr: https://www.flickr.com/groups/randmnews/
  #instagram: https://www.instagram.com/explore/tags/randmnews/

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

theme: jekyll-theme-leap-day
